const users = [{
    "id": 1,
    "first_name": "Blakeley",
    "last_name": "Bilt",
    "email": "bbilt0@aboutads.info"
  }, {
    "id": 2,
    "first_name": "De",
    "last_name": "Meale",
    "email": "dmeale1@mit.edu"
  }, {
    "id": 3,
    "first_name": "Nyssa",
    "last_name": "Swindells",
    "email": "nswindells2@google.nl"
  }, {
    "id": 4,
    "first_name": "Dixie",
    "last_name": "Bendson",
    "email": "dbendson3@icq.com"
  }, {
    "id": 5,
    "first_name": "Charmane",
    "last_name": "Shadrack",
    "email": "cshadrack4@jiathis.com"
  }, {
    "id": 6,
    "first_name": "Jarrid",
    "last_name": "Bonar",
    "email": "jbonar5@blogs.com"
  }, {
    "id": 7,
    "first_name": "Ronica",
    "last_name": "Richley",
    "email": "rrichley6@hao123.com"
  }, {
    "id": 8,
    "first_name": "Karly",
    "last_name": "Rattenbury",
    "email": "krattenbury7@devhub.com"
  }, {
    "id": 9,
    "first_name": "Teodoro",
    "last_name": "Shewon",
    "email": "tshewon8@over-blog.com"
  }, {
    "id": 10,
    "first_name": "Glen",
    "last_name": "Rawood",
    "email": "grawood9@networkadvertising.org"
  }, {
    "id": 11,
    "first_name": "Mariele",
    "last_name": "Baldassi",
    "email": "mbaldassia@forbes.com"
  }, {
    "id": 12,
    "first_name": "Gradeigh",
    "last_name": "Gration",
    "email": "ggrationb@gravatar.com"
  }, {
    "id": 13,
    "first_name": "Friedrich",
    "last_name": "Sline",
    "email": "fslinec@mail.ru"
  }, {
    "id": 14,
    "first_name": "Brooks",
    "last_name": "Menham",
    "email": "bmenhamd@constantcontact.com"
  }, {
    "id": 15,
    "first_name": "Minnaminnie",
    "last_name": "Brevetor",
    "email": "mbrevetore@cpanel.net"
  }, {
    "id": 16,
    "first_name": "Charline",
    "last_name": "Deinert",
    "email": "cdeinertf@telegraph.co.uk"
  }, {
    "id": 17,
    "first_name": "Chrissy",
    "last_name": "Batrick",
    "email": "cbatrickg@ucla.edu"
  }, {
    "id": 18,
    "first_name": "Norrie",
    "last_name": "Giraudat",
    "email": "ngiraudath@adobe.com"
  }, {
    "id": 19,
    "first_name": "Renault",
    "last_name": "Knudsen",
    "email": "rknudseni@jigsy.com"
  }, {
    "id": 20,
    "first_name": "Tore",
    "last_name": "Limerick",
    "email": "tlimerickj@tamu.edu"
  }, {
    "id": 21,
    "first_name": "Genna",
    "last_name": "Juliff",
    "email": "gjuliffk@telegraph.co.uk"
  }, {
    "id": 22,
    "first_name": "Dusty",
    "last_name": "Hollier",
    "email": "dhollierl@forbes.com"
  }, {
    "id": 23,
    "first_name": "Jody",
    "last_name": "Ruspine",
    "email": "jruspinem@upenn.edu"
  }, {
    "id": 24,
    "first_name": "Clive",
    "last_name": "Arrault",
    "email": "carraultn@sourceforge.net"
  }, {
    "id": 25,
    "first_name": "Devan",
    "last_name": "Swatheridge",
    "email": "dswatheridgeo@epa.gov"
  }]

  module.exports = users